<?php

namespace Massil\ConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BilanParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilanParameterRepository extends EntityRepository
{
}
