<?php

namespace Massil\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HepatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HepatiqueRepository extends EntityRepository
{
}
