<?php

namespace Massil\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RechercheAvanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheAvanceRepository extends EntityRepository
{
}
