<?php

namespace Massil\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EditSecurityController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Massil\UserBundle\Controller\EditSecurityController();
        return $instance;
    }
}
