<?php

namespace Massil\ConfigBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ParamController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Massil\ConfigBundle\Controller\ParamController();
        return $instance;
    }
}
