<?php

namespace Massil\MedicalBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConsultationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Massil\MedicalBundle\Controller\ConsultationController();
        return $instance;
    }
}
