parameters:
#    massil_user.example.class: Massil\UserBundle\Example

services:
#    massil_user.example:
#        class: %massil_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
