<?php

namespace Massil\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AntecedantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedantRepository extends EntityRepository
{
	public function getPatientAntecedants($id)
	{
		$query=$this->createQueryBuilder('a')
					->where('a.patient=:id')
					->setParameter('id', $id)
					->orderBy('a.dateAjoute','DESC')
					->getQuery()
					->getResult();
					
		return $query;
	}
}
