medical_config_bilan:
    path: /bilan/{bilan}
    defaults: { _controller:MassilConfigBundle:Param:setBilan }

medical_config_init:
    pattern: /init
    defaults: { _controller: MassilConfigBundle:Param:init }

medical_config_test:
    pattern: /test
    defaults: { _controller: MassilConfigBundle:Param:test }
